project:
  type: website
  output-dir: docs

website:
  title: "Open Urban Air and Meteorological Data"
  navbar:
    background: "#7A0026"
    foreground: "white"
    pinned: true
    right:
      - text: "ğŸ  Home"
        href: "https://jcaceres-academic.github.io"
      - text: "ğŸ“„ Article"
        href: "article.pdf"
      - text: "ğŸ“˜ Notebook"
        href: "notebook.html"
      - text: "ğŸ’» GitHub"
        href: "https://github.com/jcaceres-academic/OpenUrbanAirandMeteorological"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-location: left
    number-sections: false
    code-fold: false
    smooth-scroll: true
