project:
  type: website

website:
  title: "OpenUrbanAirandMeteorological"
  navbar:
    background: "#7A0026"
    pinned: true
    left:
      - text: "ğŸ  Home"
        href: "https://jcaceres-academic.github.io/"
        target: "_blank"
      - text: "ğŸ“ Project"
        href: "index.html"
      - text: "ğŸ“„ Article"
        href: "article.pdf"
        id: "article-link"
      - text: "ğŸ“˜ Notebook"
        href: "notebook.html"
      - text: "ğŸ’» GitHub"
        href: "https://github.com/jcaceres-academic/OpenUrbanAirandMeteorological"

format:
  html:
    theme: cosmo
    toc: true
    toc-location: left
    smooth-scroll: true
    page-navigation: true
    css: styles.css
