project:
  type: website
  output-dir: .

website:
  title: "Open Urban Air and Meteorological Data"
  navbar:
    background: "#7A0026"
    logo: ""
    right:
      - text: "ğŸ  Home"
        href: index.html
      - text: "ğŸ“„ Article"
        href: article.pdf
      - text: "ğŸ“˜ Notebook"
        href: notebook.html
      - text: "ğŸ’» GitHub"
        href: https://github.com/jcaceres-academic/OpenUrbanAirandMeteorological
  page-navigation: true
  search: false

format:
  html:
    theme: cosmo
    css: styles.css  
    toc: true
    toc-location: left
    toc-title: "On this page"
    link-external-icon: false
    smooth-scroll: true
    number-sections: false
    code-copy: true
    code-overflow: wrap
    allow-html: true

editor: visual

